# Required
version: 2

# Image to use
build:
  image: testing

 #configuration
 python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: brendanmapes/littlesis
